version: '3'
services:
  web:
    build: .
    ports:
      - "8081:80" # Maps port 8081 on your host to port 80 in the container
    volumes:
      - .:/usr/share/nginx/html # Mount the root directory to serve the HTML files and assets
